name: Build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
